[package]
name = "sha256-zkasm"
version = "0.1.0"
edition = "2021"

# This is necessary to generate a '.wasm' file.
[lib]
crate-type = ["cdylib"]

[dependencies]
panic-halt = "0.2.0"
sha2 = { version = "0.10.8", default-features = false }
